constr_fin/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic import RedirectView
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

"""
This module contains the URL patterns for the constr_fin app.
"""

schema_view = get_schema_view(
    openapi.Info(
        title="Django Construction Financing Schedule API",
        default_version='v0.1.2',
        description="API documentation for Django Construction Financing Schedule",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="abaybula@gmail.com"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('schedule.urls')),
    path('api/', include('schedule.urls')),
    path('', RedirectView.as_view(url='/schedule/', permanent=True)),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api-auth/', include('rest_framework.urls')),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from rest_framework.reverse import reverse_lazy

from users import views
from users.views import UserPasswordChange

"""
This module contains the URL patterns for the users app.
"""

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
    path('password_change/', UserPasswordChange.as_view(), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='password_change_done'),
    path('password_reset/', PasswordResetView.as_view(template_name='users/password_reset_form.html',
                                                      email_template_name='users/password_reset_email.html',
                                                      success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url=reverse_lazy('users:password_reset_done')),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('email-verification-request/', views.EmailVerificationRequest.as_view(), name='email_verification_request'),
    path('email-verification-confirm/<uidb64>/<token>/', views.EmailVerificationConfirm.as_view(),
         name='email_verification_confirm'),
    path('resend-email/', views.ResendEmail.as_view(), name='resend_email'),
    path('resend-email-done/', views.ResendEmailDone.as_view(), name='resend_email_done'),
]

users/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
    Custom user model with email as the unique identifier.
    """
    verification_uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    is_verified = models.BooleanField(default=False)

    # Add related_name arguments
    groups = models.ManyToManyField(
        'auth.Group',
        blank=True,
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
        related_name="custom_user_set",
        related_query_name="user",
        verbose_name='groups'
    )
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        blank=True,
        help_text='Specific permissions for this user.',
        related_name="custom_user_set",
        related_query_name="user",
        verbose_name='user permissions'
    )

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView
from rest_framework.views import APIView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm

User = get_user_model()


class RegisterUser(CreateView):
    """
    View for user registration.
    """
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Register'}
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """
        Handles the form validation for user registration.
        :param form: The form object.
        :return: The response object.
        """
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # Define the email subject
        mail_subject = 'Email Verification'

        # Generate the uid and token
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = default_token_generator.make_token(user)

        # Generate the email verification link
        email_verification_link = self.request.build_absolute_uri(
            reverse('users:email_verification_confirm', args=[uid, token])
        )

        # Create the email message
        message = render_to_string('users/active_email.html', {
            'user': user,
            'email_verification_link': email_verification_link,
        })
        email = EmailMessage(mail_subject, message, to=[user.email])
        email.send()

        return render(self.request, 'users/register_done.html')


class EmailVerificationRequest(APIView):
    """
    View for email verification request.
    """
    def get(self, request, *args, **kwargs):
        """
        Handles the GET request for email verification request.
        :param request: The request object.
        :param args: Additional arguments.
        :param kwargs: Additional keyword arguments.
        :return: The response object.
        """
        return render(request, 'users/confirm_email.html')


class EmailVerificationConfirm(APIView):
    """
    View for email verification confirmation.
    """
    def get(self, request, uidb64, token, *args, **kwargs):
        """
        Handles the GET request for email verification confirmation.
        :param request: The request object.
        :param uidb64: The base64-encoded user ID.
        :param token: The token for email verification.
        :param args: Additional arguments.
        :param kwargs: Additional keyword arguments.
        :return: The response object.
        """
        # Decode the user ID
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None
        # Check if the user is not None and the token is valid
        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
        # Return the response object based on the user activation status
            return render(request, 'users/activation_success.html')
        else:
            return render(request, 'users/activation_invalid.html')


class ResendEmail(APIView):
    """
    View for resending the email verification email.
    """
    def get(self, request, *args, **kwargs):
        """
        Handles the GET request for resending the email verification email.
        :param request: The request object.
        :param args: Additional arguments.
        :param kwargs: Additional keyword arguments.
        :return: The response object.
        """
        # Check if the user is authenticated
        if not request.user.is_authenticated:
            # Redirect to the login page if the user is not authenticated
            return redirect('users:login')

        # Get the user
        user = request.user

        # Check if the user is not active
        if not user.is_active:
            # Define the email subject
            mail_subject = 'Email Verification'

            # Generate the uid and token
            uid = urlsafe_base64_encode(force_bytes(user.pk))
            token = default_token_generator.make_token(user)

            # Generate the email verification link
            email_verification_link = request.build_absolute_uri(
                reverse('users:email_verification_confirm', args=[uid, token])
            )

            # Create the email message
            message = render_to_string('users/active_email.html', {
                'user': user,
                'email_verification_link': email_verification_link,
            })
            email = EmailMessage(mail_subject, message, to=[user.email])
            email.send()

        return render(request, 'users/resend_email_done.html')


class ResendEmailDone(APIView):
    """
    View for resending the email verification email done.
    """
    def get(self, request, *args, **kwargs):
        """
        Handles the GET request for resending the email verification email done.
        :param request: The request object.
        :param args: Additional arguments.
        :param kwargs: Additional keyword arguments.
        :return: The response object.
        """
        return render(request, 'users/resend_email_done.html')


class LoginUser(LoginView):
    """
    View for user login.
    """
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Login'}


class ProfileUser(LoginRequiredMixin, UpdateView):
    """
    View for user profile update.
    """
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': 'Profile'}

    def get_success_url(self):
        """
        Returns the success URL for the current user profile.
        :return: A string representing the success URL for the user profile.
        """
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """
        Returns the current user object.
        :param queryset: An optional queryset to filter the user object.
        :return: The current user object.
        """
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    """
    View for user password change.
    """
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('users:password_change_done')
    template_name = 'users/password_change_form.html'

users/templates/users/activation_invalid.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Activation error template -->
    <h1>{% blocktranslate %}Email Verification Failed{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}We're sorry, but the email verification failed. Please try again.{% endblocktranslate %}</p>
    <a href="{% url 'users:register' %}">{% blocktranslate %}Click here to register again{% endblocktranslate %}</a>
{% endblock content %}

users/templates/users/activation_success.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Activation successful template -->
    <h1>{% blocktranslate %}Email Verification Successful{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}Thank you,{% endblocktranslate %} {{ user.username }}. {% blocktranslate %}Your email has been successfully verified.{% endblocktranslate %}</p>
    <a href="{% url 'users:login' %}">{% blocktranslate %}Click here to login{% endblocktranslate %}</a>
{% endblock content %}

users/templates/users/active_email.html
{% load i18n %}
{% autoescape off %}
    {% blocktranslate %}Hi{% endblocktranslate %} {{ user.username }},

    {% blocktranslate %}Please click on the link below to verify your email and activate your account:{% endblocktranslate %}

    {{ email_verification_link }}

    {% blocktranslate %}If you did not make this request, please ignore this email.{% endblocktranslate %}
{% endautoescape %}

users/templates/users/confirm_email.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Email confirmation template -->
    <h2>{% blocktranslate %}Email confirmation{% endblocktranslate %}</h2>
    <p>{% blocktranslate %}Please check your email to verify your account.{% endblocktranslate %}</p>
    <p>{% blocktranslate %}If you did not receive an email, you can {% endblocktranslate %}<a href="{{ url }}">{% blocktranslate %}request a new email{% endblocktranslate %}</a>.</p>
{% endblock content %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Login form -->
    <h1>{% blocktranslate %}Login{% endblocktranslate %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }} </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <p><button type="submit">{% blocktranslate %}Login{% endblocktranslate %}</button></p>
        <!-- Password reset link -->
        <p><a href="{% url 'users:password_reset' %}">{% blocktranslate %}Forgot password?{% endblocktranslate %}</a></p>
    </form>
{% endblock content %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Password change successful template -->
    <h1>{% blocktranslate %}Password change successful{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}You changed your password {% endblocktranslate %}<a href="{% url 'users:profile' %}">{% blocktranslate %}back to profile{% endblocktranslate %}</a></p>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <!-- Password reset form -->
    <h1>{% blocktranslate %}New password{% endblocktranslate %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }} </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <p><button type="submit">{% blocktranslate %}Save{% endblocktranslate %}</button></p>
    </form>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <!-- Password reset from email successful template -->
    <h1>{% blocktranslate %}Password reset{% endblocktranslate %}</h1>
    <p>{% translate "We've emailed you instructions for setting your password. If an account exists with the email you entered, you should receive them shortly." %}</p>
    <p>{% translate "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
{% endblock content %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
    <!-- Password reset email template -->
    {% blocktranslate %}You're receiving this email because you requested a password reset for your user account.{% endblocktranslate %}
    {% translate "Please go to the following page and choose a new password:" %}
    {% block reset_link %}{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}{% endblock %}
    {% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}
    {% translate "Thanks for using site!" %}
{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <!-- Password reset from email form -->
    <h1>{% blocktranslate %}Password reset{% endblocktranslate %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }} </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <p><button type="submit">{% blocktranslate %}Password reset{% endblocktranslate %}</button></p>
    </form>
{% endblock content %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Profile form -->
    <h1>{% blocktranslate %}Profile{% endblocktranslate %}</h1>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }} </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <p><button type="submit">{% blocktranslate %}Save{% endblocktranslate %}</button></p>
    </form>
    <!-- Password change link -->
    <p><a href="{% url 'users:password_change' %}">{% blocktranslate %}Change password{% endblocktranslate %}</a></p>
{% endblock content %}

users/templates/users/register.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <!-- Register form -->
    <h1>{% blocktranslate %}Register a new account.{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}Already have an account? {% endblocktranslate %}<a href="{% url 'users:login' %}">{% blocktranslate %}Log in{% endblocktranslate %}</a>.</p>
    <form method="post">
        {% csrf_token %}
        <div class="form-error">{{ form.non_field_errors }}</div>
        {% for field in form %}
            <p><label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }} </p>
            <div class="form-error">{{ field.errors }}</div>
        {% endfor %}
        <p><button type="submit">{% blocktranslate %}Register{% endblocktranslate %}</button></p>
    </form>
{% endblock content %}

users/templates/users/register_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Registration successful template -->
    <h1>{% blocktranslate %}Registration Successful{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}Thank you for registering, {% endblocktranslate %}{{ user.username }}. {% blocktranslate %}Please check your email to verify your account.{% endblocktranslate %}</p>
    <p>{% blocktranslate %}If you did not receive an email, you can {% endblocktranslate %}<a href="{% url 'users:resend_email' %}">{% blocktranslate %}request a new email{% endblocktranslate %}</a>.</p>
    <a href="{% url 'users:login' %}">{% blocktranslate %}Click here to login{% endblocktranslate %}</a>
{% endblock content %}

users/templates/users/resend_email_done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <!-- Resend email done template -->
    <h1>{% blocktranslate %}Email Verification Link Resent{% endblocktranslate %}</h1>
    <p>{% blocktranslate %}We have resent the email verification link to your email address. Please check your email and click on the link to verify your email.{% endblocktranslate %}</p>
    <a href="{% url 'users:login' %}">{% blocktranslate %}Click here to login{% endblocktranslate %}</a>
{% endblock content %}